### PR TITLE
Filter non stork configs and read them as optional values

### LINKED ISSUE #1201: Microprofile Provider: Stork should only call config.getValue() on properties related to Stork
Initializing Stork results in an exception if there are any configuration properties with empty strings as values.

**Code to reproduce**
```java
SmallRyeConfig config = new SmallRyeConfigBuilder()
      .addDefaultSources()
      .build();

ConfigProviderResolver.instance().registerConfig(config, null);

Stork.initialize();
```
If there are empty system properties or environmental variables, the stork `MicroProfileConfigProvider` will throw an exception as it eagerly reads the configuration values for all existing properties:

[**Source**](https://github.com/smallrye/smallrye-stork/blob/main/microprofile/src/main/java/io/smallrye/stork/microprofile/MicroProfileConfigProvider.java)
```java
for (String propertyName : config.getPropertyNames()) {
    StorkConfigUtils.computeServiceProperty(propertiesByServiceName, propertyName,
            config.getValue(propertyName, String.class));
}
```

**The resulting exception**

`SRCFG00040: The config property user.script is defined as the empty String ("") which the following Converter considered to be null: io.smallrye.config.Converters$BuiltInConverter`

Currently I have solved this issue by adding a custom interceptor to the config provider, but I don't see why Stork needs to read the values of all properties, it really should filter them and only read the ones related to Stork (`stork.*`).

**Versions I have used:**

- JDK 21 Eclipse Temurin 21.0.4
- Maven 3.9.12
- io.smallrye.config:smallrye-config-core 3.16.0
- io.smallrye.stork:stork-core 2.7.9
- io.smallrye.stork:stork-microprofile-config 2.7.9

### PR DESCRIPTION
**Pull request by aureamunoz**
Fixes #1201

### CODE REVIEW

File: microprofile/src/test/java/io/smallrye/stork/microprofile/MicroProfileConfigProviderTest.java [hunk 1]
```diff
@@ -233,6 +233,27 @@ void shouldHandleServiceNamesInQuotes() {
         assertThat(lb.getType()).isEqualTo("test-lb-2");
     }
 
+    @Test
+    void shouldIgnorePropertiesWithEmptyValues() {
```
Comment (cescoffier) [inline microprofile/src/test/java/io/smallrye/stork/microprofile/MicroProfileConfigProviderTest.java]: Something like `shouldFilterNonStorkPropertiesAndIgnoreEmptyValues` would be sightly better.

File: microprofile/src/main/java/io/smallrye/stork/microprofile/MicroProfileConfigProvider.java [hunk 2]
```diff
@@ -32,8 +33,11 @@ public MicroProfileConfigProvider() {
         Map<String, Map<String, String>> propertiesByServiceName = new HashMap<>();
 
         for (String propertyName : config.getPropertyNames()) {
-            StorkConfigUtils.computeServiceProperty(propertiesByServiceName, propertyName,
-                    config.getValue(propertyName, String.class));
+            if (propertyName.startsWith(Stork.STORK + ".")) {
+                config.getOptionalValue(propertyName, String.class)
+                        .ifPresent(value -> StorkConfigUtils.computeServiceProperty(propertiesByServiceName,
```
Comment (cescoffier) [inline microprofile/src/main/java/io/smallrye/stork/microprofile/MicroProfileConfigProvider.java]: Maybe add ` log.debug("Ignoring empty stork config property: {}", propertyName)` just in case.

**Review by cescoffier — DISMISSED** [review]
Just 2 minor comments.

**Comment by cescoffier** [comment]
The Spring Boot config provider doesn't have the equivalent filtering / optional value handling:

```java
for (String propertyName : getPropertyNames(environment)) {
    StorkConfigUtils.computeServiceProperty(propertiesByServiceName, propertyName,
            environment.getProperty(propertyName));
}
```

Should we add it there too?

**Review by cescoffier — DISMISSED** [review]

**Comment by aureamunoz** [comment]
> The Spring Boot config provider doesn't have the equivalent filtering / optional value handling:
> 
> ```java
> for (String propertyName : getPropertyNames(environment)) {
>     StorkConfigUtils.computeServiceProperty(propertiesByServiceName, propertyName,
>             environment.getProperty(propertyName));
> }
> ```
> 
> Should we add it there too?

Yes, I think so for consistency. I saw it at some point but didn't do. It's done in last commit.

File: spring-boot/src/main/java/io/smallrye/stork/springboot/SpringBootConfigProvider.java [hunk 3]
```diff
@@ -26,10 +27,12 @@ public SpringBootConfigProvider() {
...
 
         for (String propertyName : getPropertyNames(environment)) {
-
-            StorkConfigUtils.computeServiceProperty(propertiesByServiceName, propertyName,
-                    environment.getProperty(propertyName));
-
+            if (propertyName.startsWith(Stork.STORK + ".")) {
+                String value = environment.getProperty(propertyName);
+                if (value != null && !value.isEmpty()) {
+                    StorkConfigUtils.computeServiceProperty(propertiesByServiceName, propertyName, value);
```
Comment (cescoffier) [inline spring-boot/src/main/java/io/smallrye/stork/springboot/SpringBootConfigProvider.java]: Should we log otherwise, as we do in MP?

File: spring-boot/src/main/java/io/smallrye/stork/springboot/SpringBootConfigProvider.java [hunk 4]
```diff
@@ -26,10 +27,12 @@ public SpringBootConfigProvider() {
         Map<String, Map<String, String>> propertiesByServiceName = new HashMap<>();
 
         for (String propertyName : getPropertyNames(environment)) {
-
-            StorkConfigUtils.computeServiceProperty(propertiesByServiceName, propertyName,
-                    environment.getProperty(propertyName));
-
+            if (propertyName.startsWith(Stork.STORK + ".")) {
+                String value = environment.getProperty(propertyName);
+                if (value != null && !value.isEmpty()) {
```
Comment (cescoffier) [inline spring-boot/src/main/java/io/smallrye/stork/springboot/SpringBootConfigProvider.java]: Wondering if we should trim the value first and avoid 0-length values. Not sure.

File: microprofile/src/main/java/io/smallrye/stork/microprofile/MicroProfileConfigProvider.java [hunk 5]
```diff
@@ -32,8 +33,13 @@ public MicroProfileConfigProvider() {
...
 
         for (String propertyName : config.getPropertyNames()) {
-            StorkConfigUtils.computeServiceProperty(propertiesByServiceName, propertyName,
-                    config.getValue(propertyName, String.class));
+            if (propertyName.startsWith(Stork.STORK + ".")) {
+                config.getOptionalValue(propertyName, String.class)
+                        .ifPresentOrElse(
+                                value -> StorkConfigUtils.computeServiceProperty(propertiesByServiceName,
+                                        propertyName, value),
+                                () -> log.debug("Ignoring empty Stork config property: {}", propertyName));
```
Comment (cescoffier) [inline microprofile/src/main/java/io/smallrye/stork/microprofile/MicroProfileConfigProvider.java]: Stork or stork? Our logging seems to be slightly inconsistent.

**Review by cescoffier — DISMISSED** [review]
See a few minor comments, but nothing is holding the merge.

File: spring-boot/src/main/java/io/smallrye/stork/springboot/SpringBootConfigProvider.java (hunk 4 above)
Comment (aureamunoz) [reply spring-boot/src/main/java/io/smallrye/stork/springboot/SpringBootConfigProvider.java]: Yes, let's do it I think it's a good idea. It doesn't cost anything, and a value with blank spaces isn't usually intentional.

**Comment by aureamunoz** [comment]
I need your approval again to merge

**Review by cescoffier — APPROVED** [review]
