### PR TITLE
Remove schema for host and use 0 as default port in knative

### LINKED ISSUE #488: Knative SD implementation doesn't get the correct service instance endpoint
From [this PR](https://github.com/quarkusio/quarkus/pull/30272)

The knative service discovery strategy is not working correctly. Given the quarkus-super-heroes project, when curl the rest-fights app on the /api/fights/randomfighters endpoint I would expect to see two random fighters, but I don’t. I see the fallback fighters
```
╰─ http https://rest-fights-eric-deandrea-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com/api/fights/randomfighters
HTTP/1.1 200 OK
cache-control: private
content-length: 314
content-type: application/json;charset=UTF-8
date: Mon, 06 Feb 2023 16:39:59 GMT
server: envoy
set-cookie: f876558f2b90f5b848dd878960dd0dc7=539d5cd9b01519008a395f7357457294; path=/; HttpOnly
x-envoy-upstream-service-time: 859

{
    "hero": {
        "level": 1,
        "name": "Fallback hero",
        "picture": "https://dummyimage.com/280x380/1e8fff/ffffff&text=Fallback+Hero",
        "powers": "Fallback hero powers"
    },
    "villain": {
        "level": 45,
        "name": "Fallback villain",
        "picture": "https://dummyimage.com/280x380/b22222/ffffff&text=Fallback+Villain",
        "powers": "Fallback villain powers"
    }
}
```
To reproduce: 
using https://developers.redhat.com/developer-sandbox
https://github.com/edeandrea/quarkus-super-heroes/tree/fix-stork
Steps to deploy:
Make sure you’re using Java 17!
1 - oc apply -f https://raw.githubusercontent.com/edeandrea/quarkus-super-heroes/fix-stork/rest-villains/deploy/k8s/java17-knative.yml
2 - oc apply -f https://raw.githubusercontent.com/edeandrea/quarkus-super-heroes/fix-stork/rest-heroes/deploy/k8s/java17-knative.yml
3 - Clone https://github.com/edeandrea/quarkus-super-heroes and switch to the fix-stork branch
4 - 
```
cd quarkus-super-heroes/rest-fights
./mvnw clean package -DskipTests \
  -Dquarkus.profile=knative-openshift-17 \
  -Dquarkus.container-image.registry=image-registry.openshift-image-registry.svc:5000 \
  -Dquarkus.container-image.group=$(oc project -q) \
  -Dquarkus.knative.labels.\"app.openshift.io/runtime\"=quarkus \
  -Dquarkus.knative.version=1.0 \
  -Dquarkus.kubernetes.deploy=true
```

### PR DESCRIPTION
**Pull request by aureamunoz**
Fixes #488

### CODE REVIEW

File: service-discovery/knative/src/main/java/io/smallrye/stork/servicediscovery/knative/KnativeServiceDiscovery.java [hunk 1]
```diff
@@ -147,9 +148,21 @@ private List<ServiceInstance> toStorkServiceInstances(List<Service> knServices,
...
+                try {
+                    URI uri = new URI(knService.getStatus().getUrl());
+                    if (uri != null && uri.getScheme() != null) {
+                        host = uri.getHost();
+                        if (host == null) { // invalid URI
+                            throw new IllegalArgumentException("Invalid URL used: '" + uri + "'");
+                        }
+                    }
+                } catch (Exception e) {
+                    e.printStackTrace();
```
Comment (cescoffier) [inline service-discovery/knative/src/main/java/io/smallrye/stork/servicediscovery/knative/KnativeServiceDiscovery.java:161]: Should be a logger.

File: service-discovery/knative/src/main/java/io/smallrye/stork/servicediscovery/knative/KnativeServiceDiscovery.java [hunk 2]
```diff
@@ -147,9 +148,21 @@ private List<ServiceInstance> toStorkServiceInstances(List<Service> knServices,
...
+                }
 
                 serviceInstances
-                        .add(new DefaultServiceInstance(ServiceInstanceIds.next(), knService.getStatus().getUrl(), 8080, secure,
+                        .add(new DefaultServiceInstance(ServiceInstanceIds.next(), host, 0, secure,
```
Comment (cescoffier) [inline service-discovery/knative/src/main/java/io/smallrye/stork/servicediscovery/knative/KnativeServiceDiscovery.java:165]: I'm a bit concerned by port 0. Port 0 in system has a semantic (picking a random available port). To denote the absence of port, -1 would be better.

File: service-discovery/knative/src/test/java/io/smallrye/stork/servicediscovery/knative/KnativeServiceDiscoveryRealClusterTest.java [hunk 3]
```diff
@@ -0,0 +1,96 @@
...
+                .onFailure().invoke(th -> fail("Failed to get service instances from the cluster", th))
+                .subscribe().with(instances::set);
+
+        await().atMost(Duration.ofSeconds(40))
+                .until(() -> instances.get() != null);
+
+        assertThat(instances.get()).hasSize(1);
+        ServiceInstance svcInstance = instances.get().get(0);
+
+        // This code needs the smallrye-mutiny-vertx-web-client dependency
```
Comment (cescoffier) [inline service-discovery/knative/src/test/java/io/smallrye/stork/servicediscovery/knative/KnativeServiceDiscoveryRealClusterTest.java:57]: Why is this part commented out?

File: service-discovery/knative/src/test/java/io/smallrye/stork/servicediscovery/knative/KnativeServiceDiscoveryRealClusterTest.java [hunk 4]
```diff
@@ -0,0 +1,96 @@
...
+                .onFailure().invoke(th -> fail("Failed to get service instances from the cluster", th))
+                .subscribe().with(instances::set);
+
+        await().atMost(Duration.ofSeconds(5))
+                .until(() -> instances.get() != null);
+
+        assertThat(instances.get()).hasSize(1);
+        ServiceInstance svcInstance = instances.get().get(0);
+
+        //        WebClient client = WebClient.create(Vertx.vertx(), new WebClientOptions()
```
Comment (cescoffier) [inline service-discovery/knative/src/test/java/io/smallrye/stork/servicediscovery/knative/KnativeServiceDiscoveryRealClusterTest.java:88]: Same here.

**Review by cescoffier — CHANGES_REQUESTED** [review]

File: service-discovery/knative/src/main/java/io/smallrye/stork/servicediscovery/knative/KnativeServiceDiscovery.java (hunk 2 above)
Comment (aureamunoz) [reply service-discovery/knative/src/main/java/io/smallrye/stork/servicediscovery/knative/KnativeServiceDiscovery.java:165]: OK. I was using 0 because seen that Quarkus recalculated it if 0. I agree that `-1` represents better what we want here. (and it works with the Quarkus extension and request filtering)

File: service-discovery/knative/src/test/java/io/smallrye/stork/servicediscovery/knative/KnativeServiceDiscoveryRealClusterTest.java (hunk 3 above)
Comment (aureamunoz) [reply service-discovery/knative/src/test/java/io/smallrye/stork/servicediscovery/knative/KnativeServiceDiscoveryRealClusterTest.java:57]: Well, this is a `@Disabled`test that I was using to be sure that the service was reachable that's why I added the dependency and the call using `WebClient`. I commented out to avoid the dependency adding.

File: service-discovery/knative/src/test/java/io/smallrye/stork/servicediscovery/knative/KnativeServiceDiscoveryRealClusterTest.java (hunk 4 above)
Comment (aureamunoz) [reply service-discovery/knative/src/test/java/io/smallrye/stork/servicediscovery/knative/KnativeServiceDiscoveryRealClusterTest.java:88]: see response above

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
could you rebase to get the CI fix?
